{% set version = '0.1.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sourcetools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sourcetools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sourcetools/sourcetools_{{ version }}.tar.gz
  sha256: 47984406efb3b3face133979ccbae9fefb7360b9a6ca1a1c11473681418ed2ca

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sourcetools')"           # [not win]
    - "\"%R%\" -e \"library('sourcetools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=sourcetools
  license: MIT + file LICENSE
  summary: Tools for the reading and tokenization of R code. The 'sourcetools' package provides
    both an R and C++ interface for the tokenization of R code, and helpers for interacting
    with the tokenized representation of R code.
  license_family: MIT

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: sourcetools
# Type: Package
# Title: Tools for Reading, Tokenizing and Parsing R Code
# Version: 0.1.7
# Author: Kevin Ushey
# Maintainer: Kevin Ushey <kevinushey@gmail.com>
# Description: Tools for the reading and tokenization of R code. The 'sourcetools' package provides both an R and C++ interface for the tokenization of R code, and helpers for interacting with the tokenized representation of R code.
# License: MIT + file LICENSE
# LazyData: TRUE
# Depends: R (>= 3.0.2)
# Suggests: testthat
# RoxygenNote: 5.0.1
# BugReports: https://github.com/kevinushey/sourcetools/issues
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2018-04-25 03:19:22 UTC; kevin
# Repository: CRAN
# Date/Publication: 2018-04-25 03:38:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
